controller_frequency: 8.0
recovery_behavior_enabled: False
conservative_reset_dist: 0.5
holonomic_robot: true


NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.01 # A tolerance on the goal point for the planner.

TebLocalPlannerROS:
  acc_lim_x: 2
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.32
  min_vel_x: 0.0
  max_vel_y: 0.2
  min_vel_y: 0

  max_vel_trans: 0.3
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.0
  
  footprint_model:
    type: "circular"
    radius: 0.225
  yaw_goal_tolerance: 0.02
  xy_goal_tolerance: 0.05

  #obstacle parameters
  min_obstacle_dist: 0.25


# DWAPlannerROS:
#   # Robot configuration parameters  
#   acc_lim_x: 2
#   acc_lim_y: 0
#   acc_lim_th: 3.2

#   max_vel_x: 0.32
#   min_vel_x: 0.0
#   max_vel_y: 0
#   min_vel_y: 0

#   max_vel_trans: 0.3
#   min_vel_trans: 0.1
#   max_vel_theta: 1.0
#   min_vel_theta: 0.0
  

  # Goal Tolerance Parameters
  
  #latch_xy_goal_tolerance: false