obstacle_range: 2.5
raytrace_range: 3.0


# footprint: [[0.225, 0.0], [0.199, 0.078], [0.141, 0.141], [0.078, 0.199], [0.0, 0.225], [-0.078, 0.199], [-0.141, 0.141], [-0.199, 0.078], [-0.225, 0.0], [-0.199, -0.078], [-0.141, -0.141], [-0.078, -0.199], [0.0, -0.225], [0.078, -0.199], [0.141, -0.141], [0.199, -0.078]]

# robot_radius: 0.225
inflation_radius: 0.3
update_frequency: 4.0
transform_tolerance: 0.5

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}









# footprint_clearing_enabled: true

# #layer definitions
# static:
#     map_topic: map
#     subscribe_to_updates: true
    

# obstacles_laser:
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

