obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.225
inflation_radius: 0.3
transform_tolerance: 6.0 #dodano
map_type: costmap #dodano

#observation_sources: laser_scan_sensor point_cloud_sensor

#laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud, topic: distance_sensors, marking: true, clearing: true}


footprint_clearing_enabled: true

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_sensor 
    laser_sensor: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, expected_update_rate: 0.0, observation_persistence: 0.0}
    #point_cloud_sensor: {data_type: PointCloud, clearing: false, marking: true, topic: distance_sensors, obstacle_range: 0.7, expected_update_rate: 0.0, observation_persistence: 0.0}

inflation:
    inflation_radius: 0.25
    cost_scaling_factor: 1
