// Generated by gencpp from file robotino_msgs/SetNsCeilHeightRequest.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHTREQUEST_H
#define ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_msgs
{
template <class ContainerAllocator>
struct SetNsCeilHeightRequest_
{
  typedef SetNsCeilHeightRequest_<ContainerAllocator> Type;

  SetNsCeilHeightRequest_()
    : height(0.0)  {
    }
  SetNsCeilHeightRequest_(const ContainerAllocator& _alloc)
    : height(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetNsCeilHeightRequest_

typedef ::robotino_msgs::SetNsCeilHeightRequest_<std::allocator<void> > SetNsCeilHeightRequest;

typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightRequest > SetNsCeilHeightRequestPtr;
typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightRequest const> SetNsCeilHeightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator1> & lhs, const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator1> & lhs, const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "384d8dd5cbcb4f6e145e6b246fa635b2";
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x384d8dd5cbcb4f6eULL;
  static const uint64_t static_value2 = 0x145e6b246fa635b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_msgs/SetNsCeilHeightRequest";
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n"
;
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNsCeilHeightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_msgs::SetNsCeilHeightRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHTREQUEST_H
