// Generated by gencpp from file robotino_msgs/SetNsCeilHeight.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHT_H
#define ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHT_H

#include <ros/service_traits.h>


#include <robotino_msgs/SetNsCeilHeightRequest.h>
#include <robotino_msgs/SetNsCeilHeightResponse.h>


namespace robotino_msgs
{

struct SetNsCeilHeight
{

typedef SetNsCeilHeightRequest Request;
typedef SetNsCeilHeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNsCeilHeight
} // namespace robotino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_msgs::SetNsCeilHeight > {
  static const char* value()
  {
    return "a9048e8c46aa7a86c2a91424f7423dad";
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeight&) { return value(); }
};

template<>
struct DataType< ::robotino_msgs::SetNsCeilHeight > {
  static const char* value()
  {
    return "robotino_msgs/SetNsCeilHeight";
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeight&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_msgs::SetNsCeilHeightRequest> should match
// service_traits::MD5Sum< ::robotino_msgs::SetNsCeilHeight >
template<>
struct MD5Sum< ::robotino_msgs::SetNsCeilHeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_msgs::SetNsCeilHeight >::value();
  }
  static const char* value(const ::robotino_msgs::SetNsCeilHeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_msgs::SetNsCeilHeightRequest> should match
// service_traits::DataType< ::robotino_msgs::SetNsCeilHeight >
template<>
struct DataType< ::robotino_msgs::SetNsCeilHeightRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_msgs::SetNsCeilHeight >::value();
  }
  static const char* value(const ::robotino_msgs::SetNsCeilHeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_msgs::SetNsCeilHeightResponse> should match
// service_traits::MD5Sum< ::robotino_msgs::SetNsCeilHeight >
template<>
struct MD5Sum< ::robotino_msgs::SetNsCeilHeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_msgs::SetNsCeilHeight >::value();
  }
  static const char* value(const ::robotino_msgs::SetNsCeilHeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_msgs::SetNsCeilHeightResponse> should match
// service_traits::DataType< ::robotino_msgs::SetNsCeilHeight >
template<>
struct DataType< ::robotino_msgs::SetNsCeilHeightResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_msgs::SetNsCeilHeight >::value();
  }
  static const char* value(const ::robotino_msgs::SetNsCeilHeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHT_H
