// Generated by gencpp from file robotino_msgs/SetNsCeilHeightResponse.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHTRESPONSE_H
#define ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_msgs
{
template <class ContainerAllocator>
struct SetNsCeilHeightResponse_
{
  typedef SetNsCeilHeightResponse_<ContainerAllocator> Type;

  SetNsCeilHeightResponse_()
    : success(false)
    , message()  {
    }
  SetNsCeilHeightResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetNsCeilHeightResponse_

typedef ::robotino_msgs::SetNsCeilHeightResponse_<std::allocator<void> > SetNsCeilHeightResponse;

typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightResponse > SetNsCeilHeightResponsePtr;
typedef boost::shared_ptr< ::robotino_msgs::SetNsCeilHeightResponse const> SetNsCeilHeightResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator1> & lhs, const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator1> & lhs, const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_msgs/SetNsCeilHeightResponse";
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNsCeilHeightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_msgs::SetNsCeilHeightResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_SETNSCEILHEIGHTRESPONSE_H
